apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-demo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata :
          labels :
            name : cron-demo

        spec:
          containers:
          - name: cron-demo
            image: centos:7
            command:
            - python
            - -c
            - from datetime import datetime; print('[{}] cron demo for ckad batch students Oracle...'.format(datetime.now()))
          restartPolicy: Never
          
